[profile.default]
solc = "0.8.27"
src = "src"
test = 'test'
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
evm_version = "shanghai"
gas_reports = ["GoatRewardPool", "GoatFeeBatch", "LayerZeroBridgeAdapter", "StrategyAdapter", "Multistrategy"]
build_info = false
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read", path = "./"}]

# Remappings in remappings.txt

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fuzz]
runs = 2048

[invariant]
runs = 256
fail_on_revert = true

[fmt]
line_length = 200
tab_width = 4
bracket_spacing = true
number_underscore = "thousands"
quote_style = "double"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}", url = "https://api.arbiscan.io/api"}
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }

[doc]
out = "documentation"