[profile.default]
solc = "0.8.27"
src = "src"
test = 'test'
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
build_info = false
fs_permissions = [{ access = "read", path = "./"}, { access = "write", path = "./"}]

remappings = [
    "forge-std/=lib/forge-std/src/",
    "src/=src/",
    "interfaces/=src/interfaces",
    "test-utils/=test/utils",
    "createx=lib/createx-forge",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@addressbook/=address-book/",
    "@properties/=lib/properties/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fuzz]
runs = 2048

[invariant]
runs = 20
depth = 1000
fail_on_revert = true

[fmt]
line_length = 200
tab_width = 4
bracket_spacing = true
number_underscore = "thousands"
quote_style = "double"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}", url = "https://api.arbiscan.io/api"}
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
sonic = { key = "${SONICSCAN_API_KEY}",  url = "https://api.sonicscan.org/api", chain = 146 }

[doc]
out = "documentation"