name: Goat Protocol Tests

on:
  pull_request:
  push:
    branches:
      - main
      - staging

jobs:
  check:
    strategy:
      fail-fast: true

    env:
      ARBITRUM_RPC_URL: ${{ secrets.ARBITRUM_RPC_URL }}

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: "Run Goat Protocol Tests"
        run: 'forge test'